

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import  QSize


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(190, 360)
        Dialog.setFixedSize(QSize(190,360))
        self.title_label = QtWidgets.QLabel(parent=Dialog)
        self.title_label.setEnabled(True)
        self.title_label.setGeometry(QtCore.QRect(20, 10, 140, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setScaledContents(True)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.length = QtWidgets.QSlider(parent=Dialog)
        self.length.setGeometry(QtCore.QRect(20, 51, 160, 31))
        self.length.setMinimum(1)
        self.length.setMaximum(20)
        self.length.setPageStep(6)
        self.length.setProperty("value", 10)
        self.length.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.length.setTickPosition(QtWidgets.QSlider.TickPosition.TicksAbove)
        self.length.setTickInterval(1)
        self.length.setObjectName("length")
        self.doUpperCase = QtWidgets.QCheckBox(parent=Dialog)
        self.doUpperCase.setGeometry(QtCore.QRect(30, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doUpperCase.setFont(font)
        self.doUpperCase.setChecked(True)
        self.doUpperCase.setAutoRepeat(False)
        self.doUpperCase.setObjectName("doUpperCase")
        self.doNumbers = QtWidgets.QCheckBox(parent=Dialog)
        self.doNumbers.setGeometry(QtCore.QRect(30, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doNumbers.setFont(font)
        self.doNumbers.setChecked(True)
        self.doNumbers.setAutoRepeat(False)
        self.doNumbers.setObjectName("doNumbers")
        self.doSymbols = QtWidgets.QCheckBox(parent=Dialog)
        self.doSymbols.setGeometry(QtCore.QRect(30, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doSymbols.setFont(font)
        self.doSymbols.setChecked(True)
        self.doSymbols.setAutoRepeat(False)
        self.doSymbols.setObjectName("doSymbols")
        self.generate = QtWidgets.QPushButton(parent=Dialog)
        self.generate.setGeometry(QtCore.QRect(10, 190, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.generate.setFont(font)
        self.generate.setObjectName("generate")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(13, 250, 161, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_label.setText(_translate("Dialog", "PazzGen"))
        self.length.setWhatsThis(_translate("Dialog", "Length"))
        self.doUpperCase.setText(_translate("Dialog", "Uppercase"))
        self.doNumbers.setText(_translate("Dialog", "Numbers"))
        self.doSymbols.setText(_translate("Dialog", "Symbols"))
        self.generate.setText(_translate("Dialog", "Generate"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Password will be displayed here."))
